name: CI

on: [push]

jobs:
  # format:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup | Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup | Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "16"

  #     - name: Setup | Yarn Install
  #       uses: bahmutov/npm-install@v1

  #     - name: Format | Prettier Check
  #       run: yarn format --check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Setup | Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup | Yarn
        uses: bahmutov/npm-install@v1

      - name: Test | Jest
        run: yarn test --forceExit

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Setup | Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup | Yarn Install
        uses: bahmutov/npm-install@v1

      - name: Test | Jest
        run: yarn build
